[General]
Name=KERNELOS
Description=KERNELOS SDDM Theme
Type=sddm-theme
Author=Capy
Version=1.0
License=GPLv3
Website=https://github.com/Raveliop/RDP
MainScript=Main.qml
ConfigFile=theme.conf
Theme-Id=kernelos
Theme-API=2.0
